# Generated by Django 4.2.20 on 2025-04-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShelterData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shelter_id", models.PositiveIntegerField()),
                ("shelter_name", models.CharField(max_length=255)),
                ("shelter_addy", models.CharField(max_length=255)),
                ("shelter_city", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
                ("occupancy", models.PositiveIntegerField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("amenities", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
