# Generated by Django 4.2.20 on 2025-04-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelterdata",
            name="shelter_id",
        ),
    ]
