# Generated by Django 4.2.20 on 2025-04-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_remove_shelterdata_shelter_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shelterdata",
            old_name="shelter_addy",
            new_name="addy",
        ),
        migrations.RenameField(
            model_name="shelterdata",
            old_name="shelter_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="shelterdata",
            old_name="shelter_name",
            new_name="name",
        ),
    ]
