# Generated by Django 4.2.19 on 2025-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("station_name", models.CharField(max_length=255)),
                ("precip_inches", models.IntegerField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
