# Generated by Django 4.2.20 on 2025-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField()),
                ("title", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=255)),
                ("votes", models.IntegerField()),
                ("avatar", models.CharField(max_length=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
