# Generated by Django 4.2.20 on 2025-04-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postbase",
            name="avatar",
        ),
        migrations.AlterField(
            model_name="postbase",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="postbase",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
