services:
  app:
    build:
      context: .
      args:
        - DEV=true
    container_name: stormshield-dev-app
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
      - static-stormshield-dev:/vol/static
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py init_superuser &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DJANGO_ENV=dev
      - DB_HOST=stormshield-dev-db
      - DB_NAME=devdatabase
      - DB_USER=devuser
      - DB_PASS=devpass
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_BASE_URL=${DJANGO_BASE_URL:-http://localhost:8000}
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      
      - S3_STORAGE_BACKEND=0
      - AWS_EXECUTION_ENV=0
      
      - CREATE_SUPERUSER=1
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASS=${DJANGO_SUPERUSER_PASS:-changeme}
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: stormshield-dev-db
    volumes:
      - postgres-stormshield-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdatabase
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      
  pgadmin:
    # Config adapted from: https://stackoverflow.com/a/77519799/10914922
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    user: root
    depends_on:
      - postgres
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    volumes:
      - pgadmin-stormshield-dev:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass


  coverage:
    image: nginx
    ports:
      - '8001:80'
    volumes:
      - ./server/htmlcov:/usr/share/nginx/html

volumes:
  postgres-stormshield-dev:
  static-stormshield-dev:
  pgadmin-stormshield-dev:
  
  
configs:
  pgpass:
    content: postgres:5432:*:devuser:devpass
  servers.json:
    content: |
      {
        "Servers": {
            "1": {
                "Group": "Servers",
                "Name": "Docker",
                "Host": "postgres",
                "Port": 5432,
                "MaintenanceDB": "devdatabase",
                "Username": "devuser",
                "PassFile": "/pgpass",
                "SSLMode": "prefer",
                "Favorite": true
            }
        }
      }
